services:
  db:
    image: postgres:15-alpine
    container_name: restaurant_db
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: restaurant_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d restaurant_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      args:
        HTTP_PROXY: http://10.137.18.241:8080
        HTTPS_PROXY: http://10.137.18.241:8080
        NO_PROXY: localhost,127.0.0.1,db,postgres,restaurant_backend,restaurant_frontend
    container_name: restaurant_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/restaurant_db
      - HTTP_PROXY=http://10.137.18.241:8080
      - HTTPS_PROXY=http://10.137.18.241:8080
      - NO_PROXY=localhost,127.0.0.1,db,postgres,restaurant_backend,restaurant_frontend
      - no_proxy=localhost,127.0.0.1,db,postgres,restaurant_backend,restaurant_frontend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        HTTP_PROXY: http://10.137.18.241:8080
        HTTPS_PROXY: http://10.137.18.241:8080
        NO_PROXY: localhost,127.0.0.1,db,postgres,restaurant_backend,restaurant_frontend
    container_name: restaurant_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HTTP_PROXY=http://10.137.18.241:8080
      - HTTPS_PROXY=http://10.137.18.241:8080
      - NO_PROXY=localhost,127.0.0.1,db,postgres,restaurant_backend,restaurant_frontend
      - no_proxy=localhost,127.0.0.1,db,postgres,restaurant_backend,restaurant_frontend

volumes:
  pgdata: